---
title: "Joining Plots"
author: "Hamza"
date: "02/06/2020"
output: html_document
---

### Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


#install.packages("pacman")
#install.packages("ggThemeAssist")
#install.packages("ggbeeswarm")
#install.packages("rptR")
#install.packages("lme4")
#install.packages("lmerTest")
#install.packages("wesanderson")
library(lmerTest)
library(ggThemeAssist)
library(rptR)
library(lme4)
library(readxl)
library(dplyr)
pacman::p_load(readxl, tidyr, dplyr, magrittr, lubridate, stringr, purrr)
library(sjPlot)
library(ggplot2)
library(lubridate)
library(wesanderson)
library(ggbeeswarm)
library(emmeans)
library(patchwork)
#sessionInfo()
```
#Overall plots
```{r}
Overall_plot <- plot_Tot_Dist_rptr+ plot_low_dur_rptr+ plot_mid_dur_rptr+ plot_high_dur_rptr+ plot_freezing_dur_rptr+ plot_frequency_rptr+ plot_latency_rptr + plot_layout(ncol=1)+ plot_layout(guides="collect")&
  theme(legend.position="bottom")&
   theme(legend.title=element_blank())

Overall_plot

ggsave(path = "Plots", file = "Overall_plot.jpeg", width = 6, height=7)


```

#Systematic extraction plot
```{r}
Review <- read.csv("Systematic_Extraction.csv")

p<-ggplot(data=Review, aes(x = reorder(Endpoint, Count), y=Count)) +
  geom_bar(stat="identity")+
coord_flip()+
   scale_x_discrete(labels=c("Total distance travelled/exploration"=expression(bold("Total distance travelled/exploration")), "Time spent in mid zone"=expression(bold("Time spent in mid zone")),
                              "Time spent in low zone"=expression(bold("Time spent in low zone")),"Latency to high zone"=expression(bold("Latency to high zone")),"Time spent in high zone"=expression(bold("Time spent in high zone")),"Freezing duration/frequency"=expression(bold("Freezing duration/frequency")),"Entries into high zone"=expression(bold("Entries into high zone")), parse=TRUE))+
  theme(axis.title.y=element_blank())
p
  
ggsave(path = "Plots", file = "Review.jpeg", limitsize = FALSE)
```


#Repeatabilty plot for Overall and Sex
```{r}

#Joining all tibbles for overall
Overall_Data_Joined1 <- full_join(Tot_Dist_rptr, low_dur_rptr)
Overall_Data_Joined2 <- full_join(Overall_Data_Joined1, mid_dur_rptr)
Overall_Data_Joined3 <- full_join(Overall_Data_Joined2, high_dur_rptr)
Overall_Data_Joined4 <- full_join(Overall_Data_Joined3, freezing_dur_rptr)
Overall_Data_Joined5 <- full_join(Overall_Data_Joined4, frequency_rptr)
Overall_Data_Joined_Final <- full_join(Overall_Data_Joined5, latency_rptr)

Overall_Data_Joined_Final

# #Joining all tibbles for sex
# Overall_Data_Joined1 <- full_join(Tot_Dist_rptr_sex, low_dur_rptr_sex)
# Overall_Data_Joined2 <- full_join(Overall_Data_Joined1, mid_dur_rptr_sex)
# Overall_Data_Joined3 <- full_join(Overall_Data_Joined2, high_dur_rptr_sex)
# Overall_Data_Joined4 <- full_join(Overall_Data_Joined3, freezing_dur_rptr_sex)
# Overall_Data_Joined5 <- full_join(Overall_Data_Joined4, freq_high_rptr_sex)
# Overall_Data_Joined_Final_sex <- full_join(Overall_Data_Joined5, latency_high_rptr_sex)
# 
# Overall_Data_Joined_Final_sex

Overall_New_plot <- ggplot(Overall_Data_Joined_Final, aes(x=Endpoint, y=r, colour=Condition)) +
geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3), size=1.1) +
geom_point(aes(x = Endpoint, y = r), position = position_dodge(0.3), size=3)+
geom_hline(yintercept = 0, lty = "dotted") +
coord_flip()+
ylim(-0.2, 0.9)+
  theme(legend.position = "bottom")+
   theme(axis.title.y=element_blank())+
   theme(legend.title=element_blank())+
  scale_color_manual(values=c("#000000", "#DD8D29", "#E2D200"))+
    theme(panel.border = element_rect(colour = "black", fill=NA, size=2),axis.ticks = element_line(size=2,color="black"),axis.ticks.length=unit(0.2,"cm"),legend.position = c(0.92, 0.85))+      font("xylab",size=15)+font("xy",size=15)+font("xy.text", size = 15) +font("legend.text",size = 15)+
    theme(legend.position = "none")+
  theme(axis.title.y=element_blank())
 


Overall_New_plot

ggsave(path = "Plots", file = "Overall_plot_new.jpeg", limitsize = FALSE)

Sex_New_plot <- ggplot(Overall_Data_Joined_Final_sex, aes(x=Endpoint, y=r, colour=Condition)) +
geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3), size=1.1) +
geom_point(aes(x = Endpoint, y = r), position = position_dodge(0.3), size=3)+
geom_hline(yintercept = 0, lty = "dotted") +
coord_flip()+
ylim(-0.2, 0.9)+
facet_grid(~Tank)+
  theme(legend.position = "bottom")+
   theme(axis.title.y=element_blank())+
  # theme(axis.text.y = element_text(angle = 15))+
  scale_color_manual(values = c("#000000", "#f8766d", "#00bfc4"))+
    theme(panel.border = element_rect(colour = "black", fill=NA, size=2),axis.ticks = element_line(size=2,color="black"),axis.ticks.length=unit(0.2,"cm"),legend.position = c(0.92, 0.85))+      font("xylab",size=15)+font("xy",size=15)+font("xy.text", size = 15) +font("legend.text",size = 15)+
    theme(legend.position = "none")+
  theme(axis.title.y=element_blank())

Sex_New_plot

ggsave(path = "Plots", file = "Overall_plot_sex.jpeg", limitsize = FALSE)


```

#Obtaining individual means and plotting them (tank only)
```{r}
#Total distance

individual_means_tot_dist_tank <- Anxiety_Joined %>%
    group_by(Fish_ID, Tank) %>%
    dplyr::summarize(Mean = mean(tot_dist, na.rm=TRUE))

individual_means_tot_dist_tank

indiv_tot_dist_tank <-ggplot(individual_means_tot_dist_tank, aes(Tank, Mean, fill=Tank)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
      scale_x_discrete(labels=c("Old" = "Short", "Tall" = "Tall"))+
  scale_fill_manual(values = wes_palette("FantasticFox1", n = 2))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean distance (cm)")+
   labs(title = "Total distance travelled")

indiv_tot_dist_tank


#Low Zone
individual_means_low_dur_tank <- Anxiety_Joined %>%
    group_by(Fish_ID, Tank) %>%
    dplyr::summarize(Mean = mean(low_dur, na.rm=TRUE))


indiv_low_dur_tank <-ggplot(individual_means_low_dur_tank, aes(Tank, Mean, fill=Tank)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
      scale_x_discrete(labels=c("Old" = "Short", "Tall" = "Tall"))+
  scale_fill_manual(values = wes_palette("FantasticFox1", n = 2))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean seconds")+
   labs(title = "Time spent in low zone")

indiv_low_dur_tank

#Mid Zone
individual_means_mid_dur_tank <- Anxiety_Joined %>%
    group_by(Fish_ID, Tank) %>%
    dplyr::summarize(Mean = mean(mid_dur, na.rm=TRUE))


indiv_mid_dur_tank <-ggplot(individual_means_mid_dur_tank, aes(Tank, Mean, fill=Tank)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
      scale_x_discrete(labels=c("Old" = "Short", "Tall" = "Tall"))+
  scale_fill_manual(values = wes_palette("FantasticFox1", n = 2))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean seconds")+
   labs(title = "Time spent in mid zone")

indiv_mid_dur_tank


#High Zone
individual_means_high_dur_tank <- Anxiety_Joined %>%
    group_by(Fish_ID, Tank) %>%
    dplyr::summarize(Mean = mean(high_dur, na.rm=TRUE))

indiv_high_dur_tank <-ggplot(individual_means_high_dur_tank, aes(Tank, Mean, fill=Tank)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
      scale_x_discrete(labels=c("Old" = "Short", "Tall" = "Tall"))+
  scale_fill_manual(values = wes_palette("FantasticFox1", n = 2))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean seconds")+
   labs(title = "Time spent in high zone")

indiv_high_dur_tank

#Freezing
individual_means_freezing_dur_tank <- Anxiety_Joined %>%
    group_by(Fish_ID, Tank) %>%
    dplyr::summarize(Mean = mean(freezing_dur, na.rm=TRUE))

indiv_freezing_dur_tank <-ggplot(individual_means_freezing_dur_tank, aes(Tank, Mean, fill=Tank)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
      scale_x_discrete(labels=c("Old" = "Short", "Tall" = "Tall"))+
  scale_fill_manual(values = wes_palette("FantasticFox1", n = 2))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean seconds")+
   labs(title = "Time spent freezing")

indiv_freezing_dur_tank


#Latency high


individual_means_latency_high_tank <- Anxiety_Joined %>%
    group_by(Fish_ID, Tank) %>%
    dplyr::summarize(Mean = mean(latency_high, na.rm=TRUE))


indiv_latency_high_tank <-ggplot(individual_means_latency_high_tank, aes(Tank, Mean, fill=Tank)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
      scale_x_discrete(labels=c("Old" = "Short", "Tall" = "Tall"))+
  scale_fill_manual(values = wes_palette("FantasticFox1", n = 2))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean latency (seconds)")+
   labs(title = "Latency to high zone")

indiv_latency_high_tank

#Entries to high
individual_means_entries_tank <- Anxiety_Joined %>%
    group_by(Fish_ID, Tank) %>%
    dplyr::summarize(Mean = mean(freq_high, na.rm=TRUE))

indiv_entries_tank <-ggplot(individual_means_entries_tank, aes(Tank, Mean, fill=Tank)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
      scale_x_discrete(labels=c("Old" = "Short", "Tall" = "Tall"))+
  scale_fill_manual(values = wes_palette("FantasticFox1", n = 2))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean entries")+
   labs(title = "Entries into high zone")

indiv_entries_tank

```



#Obtaining individual means and plotting them (sex and tank)
```{r}



#Total distance

individual_means_tot_dist <- Anxiety_Joined %>%
    group_by(Fish_ID, Sex, Tank) %>%
    dplyr::summarize(Mean = mean(tot_dist, na.rm=TRUE))

individual_means_tot_dist

indiv_tot_dist <-ggplot(individual_means_tot_dist, aes(Sex, Mean, fill=Sex)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
   facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
    scale_x_discrete(labels=c("female" = "Female", "male" = "Male"))+
   facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean distance (cm)")+
  labs(title = "Total distance travelled")

indiv_tot_dist

ggsave(path = "Plots", file = "indiv_tot_dist.jpeg", limitsize = FALSE)


#Low Zone
individual_means_low <- Anxiety_Joined %>%
    group_by(Fish_ID, Sex, Tank) %>%
    dplyr::summarize(Mean = mean(low_dur, na.rm=TRUE))

indiv_low <-ggplot(individual_means_low, aes(Sex, Mean, fill=Sex)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
  facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
    scale_x_discrete(labels=c("female" = "Female", "male" = "Male"))+
   facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean seconds")+
  labs(title = "Time spent in low zone")

ggsave(path = "Plots", file = "indiv_low_duration.jpeg", limitsize = FALSE)

#Mid Zone
individual_means_mid <- Anxiety_Joined %>%
    group_by(Fish_ID, Sex, Tank) %>%
    dplyr::summarize(Mean = mean(mid_dur, na.rm=TRUE))

indiv_mid <-ggplot(individual_means_mid, aes(Sex, Mean, fill=Sex)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
   facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
    scale_x_discrete(labels=c("female" = "Female", "male" = "Male"))+
   facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean seconds")+
  labs(title = "Time spent in mid zone")

ggsave(path = "Plots", file = "indiv_mid_dur.jpeg", limitsize = FALSE)

#High Zone
individual_means_high <- Anxiety_Joined %>%
    group_by(Fish_ID, Sex, Tank) %>%
    dplyr::summarize(Mean = mean(high_dur, na.rm=TRUE))

indiv_high <-ggplot(individual_means_high, aes(Sex, Mean, fill=Sex)) +
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
   facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
    scale_x_discrete(labels=c("female" = "Female", "male" = "Male"))+
   facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean seconds")+
  labs(title = "Time spent in high zone")

ggsave(path = "Plots", file = "indiv_high_dur.jpeg", limitsize = FALSE)

#Freezing
individual_means_freezing <- Anxiety_Joined %>%
    group_by(Fish_ID, Sex, Tank) %>%
    dplyr::summarize(Mean = mean(freezing_dur, na.rm=TRUE))

indiv_freezing <-ggplot(individual_means_freezing, aes(Sex, log(Mean)+1, fill=Sex)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
  facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
    scale_x_discrete(labels=c("female" = "Female", "male" = "Male"))+
   facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean seconds")+
  labs(title = "Time spent freezing")

ggsave(path = "Plots", file = "indiv_freezing.jpeg", limitsize = FALSE)

#Latency to high

individual_means_latency <- Anxiety_Joined %>%
    group_by(Fish_ID, Sex, Tank) %>%
    dplyr::summarize(Mean = mean(latency_high, na.rm=TRUE))

indiv_latency <-ggplot(individual_means_freezing, aes(Sex, Mean, fill=Sex)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
 facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
    scale_x_discrete(labels=c("female" = "Female", "male" = "Male"))+
   facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean latency")+
  labs(title = "Latency to high zone")

ggsave(path = "Plots", file = "indiv_latency.jpeg", limitsize = FALSE)

#Entries to high
individual_means_entries <- Anxiety_Joined %>%
    group_by(Fish_ID, Sex, Tank) %>%
    dplyr::summarize(Mean = mean(freq_high, na.rm=TRUE))

indiv_freq <-ggplot(individual_means_entries, aes(Sex, Mean, fill=Sex)) + 
   geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) + 
  geom_jitter(width = 0.2, height = 0, alpha = 0.2) +
   theme(legend.position="none")+
    scale_x_discrete(labels=c("female" = "Female", "male" = "Male"))+
   facet_grid(~Tank, labeller = labeller(Tank = tank_labs))+
  theme(axis.ticks.x=element_blank(),
       axis.title.x=element_blank())+
  labs(y="Mean entries")+
  labs(title = "Entries into high zone")

indiv_freq

ggsave(path = "Plots", file = "indiv_frequency_high.jpeg", limitsize = FALSE)


```
#Joining total variance and indiv violin plots
```{r}
Joined_violins <- Violin_Dist + Violin_Low + Violin_Mid + Violin_High + Violin_Freezing + Violin_Latency+Violin_entries + plot_layout(ncol = 2, nrow=4)

Joined_violins

Joined_violins_indiv_sex_tank <- indiv_tot_dist + indiv_low + indiv_mid + indiv_high + indiv_freezing + indiv_latency+indiv_freq + plot_layout(ncol = 2, nrow=4)

Joined_violins_indiv_sex_tank

Joined_violins_indiv_tank <- indiv_tot_dist_tank + indiv_low_dur_tank + indiv_mid_dur_tank + indiv_high_dur_tank + indiv_freezing_dur_tank + indiv_latency_high_tank+indiv_entries_tank + plot_layout(ncol = 2, nrow=4)

Joined_violins_indiv_tank
```












