---
title: "Sex_Analysis"
author: "Hamza"
date: "29/05/2020"
output: html_document
---
### Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


#install.packages("pacman")
#install.packages("ggThemeAssist")
#install.packages("ggbeeswarm")
#install.packages("rptR")
#install.packages("lme4")
#install.packages("lmerTest")
#install.packages("wesanderson")
library(lmerTest)
library(ggThemeAssist)
library(rptR)
library(lme4)
library(readxl)
library(dplyr)
pacman::p_load(readxl, tidyr, dplyr, magrittr, lubridate, stringr, purrr)
library(sjPlot)
library(ggplot2)
library(lubridate)
library(wesanderson)
library(ggbeeswarm)
library(emmeans)
library(patchwork)
library(easyGgplot2)
#sessionInfo()
```

```{r}

Old_Tanks <- read.csv("Old_tanks.csv")
Tall_Tanks <- read.csv("Tall_tanks.csv")
Anxiety_Joined <- read.csv("F1_Anxiety_Repeatability_Exp.csv")

#Inspect
str(Old_Tanks)
str(Tall_Tanks)
str(Anxiety_Joined)

#Subset by sex
Old_Tanks_Male <- subset(Old_Tanks, Old_Tanks$Sex == "male")
Old_Tanks_Female <- subset(Old_Tanks, Old_Tanks$Sex == "female")
Tall_Tanks_Male <- subset(Tall_Tanks, Tall_Tanks$Sex == "male")
Tall_Tanks_Female <- subset(Tall_Tanks, Tall_Tanks$Sex == "female")
Both_Tanks_Male <- subset(Anxiety_Joined, Anxiety_Joined$Sex == "male")
Both_Tanks_Female <- subset(Anxiety_Joined, Anxiety_Joined$Sex == "female")
```

### Total distance by sex
```{r}
hist(Old_Tanks_Male$tot_dist)
hist(Old_Tanks_Female$tot_dist)
hist(Tall_Tanks_Male$tot_dist)
hist(Tall_Tanks_Female$tot_dist)
hist(Both_Tanks_Male$tot_dist)
hist(Both_Tanks_Female$tot_dist)

Model_Tot_Dist_sex <- lmer(tot_dist ~ Tank + Sex + (1 | Fish_ID), data = Anxiety_Joined)
tab_model(Model_Tot_Dist)
hist(residuals(Model_Tot_Dist_sex))

Old_Tot_Dist_Male <- rpt(tot_dist ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_Tot_Dist_Male
plot(Old_Tot_Dist_Male)

Tall_Tot_Dist_Male <- rpt(tot_dist ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_Tot_Dist_Male


Joined_Tot_Dist_Male <- rpt(tot_dist ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Joined_Tot_Dist_Male

#Female analysis

Old_Tot_Dist_Female <- rpt(tot_dist ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_Tot_Dist_Female

Tall_Tot_Dist_Female <- rpt(tot_dist ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_Tot_Dist_Female


Joined_Tot_Dist_Female <- rpt(tot_dist ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Joined_Tot_Dist_Female

#Contrast analysis old tank

Old_Tot_Dist_Female_boot<-unlist(Old_Tot_Dist_Female$R_boot)
hist(Old_Tot_Dist_Female_boot, breaks = 50)
Old_Tot_Dist_Male_boot<-unlist(Old_Tot_Dist_Male$R_boot)
hist(Old_Tot_Dist_Male_boot, breaks = 50)

Diff_boot_Tot_Dist_old <- Old_Tot_Dist_Male_boot - Old_Tot_Dist_Female_boot
hist(Diff_boot_Tot_Dist_old, breaks = 50)

q_tot_old <- quantile(Diff_boot_Tot_Dist_old, c(0.025, 0.975)) # difference ditribuiton 95% CI
q_tot_old
mean_tot_old <- mean(Diff_boot_Tot_Dist_old)
mean_tot_old
#Significant difference

#Contrast analysis tall tank

Tall_Tot_Dist_Female_boot<-unlist(Tall_Tot_Dist_Female$R_boot)
hist(Tall_Tot_Dist_Female_boot, breaks = 50)
Tall_Tot_Dist_Male_boot<-unlist(Tall_Tot_Dist_Male$R_boot)
hist(Tall_Tot_Dist_Male_boot, breaks = 50)

Diff_boot_Tot_Dist_tall <- Tall_Tot_Dist_Male_boot - Tall_Tot_Dist_Female_boot
hist(Diff_boot_Tot_Dist_tall, breaks = 50)

q_tot_tall <- quantile(Diff_boot_Tot_Dist_tall, c(0.025, 0.975)) # difference ditribuiton 95% CI
q_tot_tall
mean_tot_tall <- mean(Diff_boot_Tot_Dist_tall)
mean_tot_tall

#Insignificant difference

```


###low duration sex
```{r}
hist(Old_Tanks_Male$low_dur)
hist(Old_Tanks_Female$low_dur)
hist(Tall_Tanks_Male$low_dur)
hist(Tall_Tanks_Female$low_dur)
hist(Both_Tanks_Male$low_dur)
hist(Both_Tanks_Female$low_dur)

Old_low_dur_Male <- rpt(low_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_low_dur_Male
plot(Old_low_dur_Male)

Tall_low_dur_Male <- rpt(low_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_low_dur_Male


Joined_low_dur_Male <- rpt(low_dur ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Joined_low_dur_Male

#Female analysis

Old_low_dur_Female <- rpt(low_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_low_dur_Female


Tall_low_dur_Female <- rpt(low_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_low_dur_Female


Joined_low_dur_Female <- rpt(low_dur ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Joined_low_dur_Female

Model_low_dur_male <- lmer(low_dur ~ Tank + (1 | Fish_ID), data = Both_Tanks_Male)
summary(Model_low_dur_male)
tab_model(Model_low_dur_male)
hist(residuals(Model_low_dur_male))

Model_low_dur_female <- lmer(low_dur ~ Tank + (1 | Fish_ID), data = Both_Tanks_Female)
summary(Model_low_dur_female)
tab_model(Model_low_dur_female)
hist(residuals(Model_low_dur_female))

#Contrast analysis old tank

Old_low_dur_Female_boot<-unlist(Old_low_dur_Female$R_boot)
hist(Old_low_dur_Female_boot, breaks = 50)
Old_low_dur_Male_boot<-unlist(Old_low_dur_Male$R_boot)
hist(Old_low_dur_Male_boot, breaks = 50)

Diff_boot_low_dur_old <- Old_low_dur_Male_boot - Old_low_dur_Female_boot
hist(Diff_boot_low_dur_old, breaks = 50)

q8 <- quantile(Diff_boot_low_dur_old, c(0.025, 0.975)) # difference ditribuiton 95% CI
m8 <- mean(Diff_boot_low_dur_old)
m8
q8

#Contrast analysis tall tank

Tall_low_dur_Female_boot<-unlist(Tall_low_dur_Female$R_boot)
hist(Tall_low_dur_Female_boot, breaks = 50)
Tall_low_dur_Male_boot<-unlist(Tall_low_dur_Male$R_boot)
hist(Tall_low_dur_Male_boot, breaks = 50)

Diff_boot_low_dur_tall <- Tall_low_dur_Male_boot - Tall_low_dur_Female_boot
hist(Diff_boot_low_dur_tall, breaks = 50)

q9 <- quantile(Diff_boot_low_dur_tall, c(0.025, 0.975)) # difference ditribuiton 95% CI
q9
m9 <- mean(Diff_boot_low_dur_tall)
m9


```

###mid duration sex
```{r}
hist(Old_Tanks_Male$mid_dur)
hist(Old_Tanks_Female$mid_dur)
hist(Tall_Tanks_Male$mid_dur)
hist(Tall_Tanks_Female$mid_dur)
hist(Both_Tanks_Male$mid_dur)
hist(Both_Tanks_Female$mid_dur)

Old_mid_dur_Male <- rpt(mid_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_mid_dur_Male


Tall_mid_dur_Male <- rpt(mid_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_mid_dur_Male


Joined_mid_dur_Male <- rpt(mid_dur ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Joined_mid_dur_Male

#Female analysis

Old_mid_dur_Female <- rpt(mid_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_mid_dur_Female


Tall_mid_dur_Female <- rpt(mid_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_mid_dur_Female


Joined_mid_dur_Female <- rpt(mid_dur ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Joined_mid_dur_Female

Model_mid_dur_male <- lmer(mid_dur ~ Tank + (1 | Fish_ID), data = Both_Tanks_Male)
summary(Model_mid_dur_male)
hist(residuals(Model_mid_dur_male))

Model_mid_dur_female <- lmer(mid_dur ~ Tank + (1 | Fish_ID), data = Both_Tanks_Female)
summary(Model_mid_dur_female)
hist(residuals(Model_mid_dur_female))

#Contrast analysis old tank

Old_mid_dur_Female_boot<-unlist(Old_mid_dur_Female$R_boot)
hist(Old_mid_dur_Female_boot, breaks = 50)
Old_mid_dur_Male_boot<-unlist(Old_mid_dur_Male$R_boot)
hist(Old_mid_dur_Male_boot, breaks = 50)

Diff_boot_mid_dur_old <- Old_mid_dur_Male_boot - Old_mid_dur_Female_boot
hist(Diff_boot_mid_dur_old, breaks = 50)

q10 <- quantile(Diff_boot_mid_dur_old, c(0.025, 0.975)) # difference ditribuiton 95% CI
q10
m10 <- mean(Diff_boot_mid_dur_old)
m10

#Contrast analysis tall tank

Tall_mid_dur_Female_boot<-unlist(Tall_mid_dur_Female$R_boot)
hist(Tall_mid_dur_Female_boot, breaks = 50)
Tall_mid_dur_Male_boot<-unlist(Tall_mid_dur_Male$R_boot)
hist(Tall_mid_dur_Male_boot, breaks = 50)

Diff_boot_mid_dur_tall <- Tall_mid_dur_Male_boot - Tall_mid_dur_Female_boot
hist(Diff_boot_mid_dur_tall, breaks = 50)

q11 <- quantile(Diff_boot_mid_dur_tall, c(0.025, 0.975)) # difference ditribuiton 95% CI
q11
m11 <- mean(Diff_boot_mid_dur_tall)
m11
```

###high duration sex
```{r}
hist(Old_Tanks_Male$high_dur)
hist(Old_Tanks_Female$high_dur)
hist(Tall_Tanks_Male$high_dur)
hist(Tall_Tanks_Female$high_dur)
hist(Both_Tanks_Male$high_dur)
hist(Both_Tanks_Female$high_dur)
# 
# Old_high_dur_Male <- rpt(high_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Male, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Old_high_dur_Male


Old_high_dur_Male2 <- rpt(sqrt(high_dur) ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_high_dur_Male2

# Tall_high_dur_Male <- rpt(high_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Male, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Tall_high_dur_Male

Tall_high_dur_Male2 <- rpt(sqrt(high_dur) ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_high_dur_Male2


Joined_high_dur_Male <- rpt(high_dur ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Joined_high_dur_Male

#Female analysis

# Old_high_dur_Female <- rpt(high_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Female, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Old_high_dur_Female


Old_high_dur_Female2 <- rpt(sqrt(high_dur) ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_high_dur_Female2

# Tall_high_dur_Female <- rpt(high_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Female, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Tall_high_dur_Female

Tall_high_dur_Female2 <- rpt(sqrt(high_dur) ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_high_dur_Female2


Joined_high_dur_Female <- rpt(high_dur ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Joined_high_dur_Female

Model_high_dur_male <- lmer(high_dur ~ Tank + (1 | Fish_ID), data = Both_Tanks_Male)
summary(Model_high_dur_male)
tab_model(Model_high_dur_male)
hist(residuals(Model_high_dur_male))

Model_high_dur2_male <- lmer(sqrt(high_dur) ~ Tank + (1 | Fish_ID), data = Both_Tanks_Male)
summary(Model_high_dur2_male)
tab_model(Model_high_dur2_male)
hist(residuals(Model_high_dur2_male))

#Contrast analysis old tank

Old_high_dur_Female_boot<-unlist(Old_high_dur_Female$R_boot)
hist(Old_high_dur_Female_boot, breaks = 50)
Old_high_dur_Male_boot<-unlist(Old_high_dur_Male$R_boot)
hist(Old_high_dur_Male_boot, breaks = 50)

Diff_boot_high_dur_old <- Old_high_dur_Female_boot - Old_high_dur_Male_boot
hist(Diff_boot_high_dur_old, breaks = 50)

q12 <- quantile(Diff_boot_high_dur_old, c(0.025, 0.975))
q12
m12 <- mean(Diff_boot_high_dur_old)
m12
#Contrast analysis tall tank

Tall_high_dur_Female_boot<-unlist(Tall_high_dur_Female$R_boot)
hist(Tall_high_dur_Female_boot, breaks = 50)
Tall_high_dur_Male_boot<-unlist(Tall_high_dur_Male$R_boot)
hist(Tall_high_dur_Male_boot, breaks = 50)

Diff_boot_high_dur_tall <- Tall_high_dur_Male_boot - Tall_high_dur_Female_boot
hist(Diff_boot_high_dur_tall, breaks = 50)

q13 <- quantile(Diff_boot_high_dur_tall, c(0.025, 0.975)) # difference ditribuiton 95% CI
q13
m13 <- mean(Diff_boot_high_dur_tall)
m13
```

###Freezing sex (is transformation necessary for some of the data ?)
```{r}
hist(Old_Tanks_Male$freezing_dur)
hist(Old_Tanks_Female$freezing_dur)
hist(Tall_Tanks_Male$freezing_dur)
hist(Tall_Tanks_Female$freezing_dur)
hist(Both_Tanks_Male$freezing_dur)
hist(Both_Tanks_Female$freezing_dur)

# Old_freezing_dur_Male <- rpt(freezing_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Male, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Old_freezing_dur_Male
# plot(Old_freezing_dur_Male) #transformation not required?
# 
# Tall_freezing_dur_Male <- rpt(freezing_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Male, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Tall_freezing_dur_Male
# plot(Tall_freezing_dur_Male)
# 
# Old_freezing_dur_Male2 <- rpt(sqrt(freezing_dur) ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Male, datatype = "Gaussian",
#     nboot = 10000, npermut = 10000)
# Old_freezing_dur_Male2
# plot(Old_freezing_dur_Male2)
# 
# Tall_freezing_dur_Male2 <- rpt(sqrt(freezing_dur) ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Male, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Tall_freezing_dur_Male2
# plot(Tall_freezing_dur_Male2)

Old_freezing_dur_Male3 <- rpt(log(freezing_dur+1) ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Male, datatype = "Gaussian",
    nboot = 10000, npermut = 10000)
Old_freezing_dur_Male3


Tall_freezing_dur_Male3 <- rpt(log(freezing_dur+1) ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_freezing_dur_Male3



# Joined_freezing_dur_Male <- rpt(freezing_dur ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Male, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Joined_freezing_dur_Male
# 
# #Female analysis
# 
# Old_freezing_dur_Female <- rpt(freezing_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Female, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Old_freezing_dur_Female
# plot(Old_freezing_dur_Female)
# 
# Tall_freezing_dur_Female <- rpt(freezing_dur ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Female, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Tall_freezing_dur_Female
# plot(Tall_freezing_dur_Female)
# 
# Old_freezing_dur_Female2 <- rpt(sqrt(freezing_dur) ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Female, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Old_freezing_dur_Female2
# plot(Old_freezing_dur_Female2)
# 
# Tall_freezing_dur_Female2 <- rpt(sqrt(freezing_dur) ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Female, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Tall_freezing_dur_Female2
# plot(Tall_freezing_dur_Female2)

Old_freezing_dur_Female3 <- rpt(log(freezing_dur+1) ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_freezing_dur_Female3


Tall_freezing_dur_Female3 <- rpt(log(freezing_dur+1) ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_freezing_dur_Female3




# Joined_freezing_dur_Female <- rpt(freezing_dur ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Female, datatype = "Gaussian", 
#     nboot = 10000, npermut = 10000)
# Joined_freezing_dur_Female
# 
# Model_freezing_dur_male <- lmer(freezing_dur ~ Tank + (1 | Fish_ID), data = Both_Tanks_Male)
# summary(Model_freezing_dur_male)
# hist(residuals(Model_freezing_dur_male))
# 
# Model_freezing_dur_female <- lmer(freezing_dur ~ Tank + (1 | Fish_ID), data = Both_Tanks_Female)
# summary(Model_freezing_dur_female)
# hist(residuals(Model_freezing_dur_female))
# 
# Model_freezing_dur_male2 <- lmer(sqrt(freezing_dur) ~ Tank + (1 | Fish_ID), data = Both_Tanks_Male)
# summary(Model_freezing_dur_male2)
# hist(residuals(Model_freezing_dur_male2))
# 
# Model_freezing_dur_female2 <- lmer(sqrt(freezing_dur) ~ Tank + (1 | Fish_ID), data = Both_Tanks_Female)
# summary(Model_freezing_dur_female2)
# hist(residuals(Model_freezing_dur_female2))

Model_freezing_dur_male3 <- lmer(log(freezing_dur+1) ~ Tank + (1 | Fish_ID), data = Both_Tanks_Male)
summary(Model_freezing_dur_male3)
hist(residuals(Model_freezing_dur_male3))
hist(residuals(Model_freezing_dur_male3))

Model_freezing_dur_female3 <- lmer(log(freezing_dur+1) ~ Tank + (1 | Fish_ID), data = Both_Tanks_Female)
summary(Model_freezing_dur_female3)
hist(residuals(Model_freezing_dur_female3))

#Contrast analysis old tank

Old_freezing_dur_Female_boot<-unlist(Old_freezing_dur_Female3$R_boot)
hist(Old_freezing_dur_Female_boot, breaks = 50)
Old_freezing_dur_Male_boot<-unlist(Old_freezing_dur_Male3$R_boot)
hist(Old_freezing_dur_Male_boot, breaks = 50)

Diff_boot_freezing_dur_old <- Old_freezing_dur_Male_boot - Old_freezing_dur_Female_boot
hist(Diff_boot_freezing_dur_old, breaks = 50)

q14 <- quantile(Diff_boot_freezing_dur_old, c(0.025, 0.975)) # difference ditribuiton 95% CI
q14
m14 <- mean(Diff_boot_freezing_dur_old)
m14

#Contrast analysis tall tank

Tall_freezing_dur_Female_boot<-unlist(Tall_freezing_dur_Female3$R_boot)
hist(Tall_freezing_dur_Female_boot, breaks = 50)
Tall_freezing_dur_Male_boot<-unlist(Tall_freezing_dur_Male3$R_boot)
hist(Tall_freezing_dur_Male_boot, breaks = 50)

Diff_boot_freezing_dur_tall <- Tall_freezing_dur_Male_boot - Tall_freezing_dur_Female_boot
hist(Diff_boot_freezing_dur_tall, breaks = 50)

q15 <- quantile(Diff_boot_freezing_dur_tall, c(0.025, 0.975)) # difference ditribuiton 95% CI
q15
m15 <- mean(Diff_boot_freezing_dur_tall)
m15


```

#Latency to high 
```{r}
Model_latency_male <- lmer(latency_high ~ Tank + (1 | Fish_ID), data = Both_Tanks_Male)
summary(Model_latency_male)
hist(residuals(Model_latency_male))

Model_latency_female <- lmer(latency_high ~ Tank + (1 | Fish_ID), data = Both_Tanks_Female)
summary(Model_latency_female)
hist(residuals(Model_latency_female))

#histogram of residuals look normal

#Male analysis


Old_latency_high_Male <- rpt(latency_high ~ + (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_latency_high_Male

Tall_latency_high_Male <- rpt(latency_high ~ + (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_latency_high_Male

Joined_latency_high_Male <- rpt(latency_high ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Joined_latency_high_Male

#Female analysis

Old_latency_high_Female <- rpt(latency_high ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_latency_high_Female

Tall_latency_high_Female <- rpt(latency_high ~ + (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_latency_high_Female

Joined_latency_high_Female <- rpt(latency_high ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Joined_latency_high_Female

#Contrast analysis old tank

Old_latency_high_Female_boot<-unlist(Old_latency_high_Female$R_boot)
hist(Old_latency_high_Female_boot, breaks = 50)
Old_latency_high_Male_boot<-unlist(Old_latency_high_Male$R_boot)
hist(Old_latency_high_Male_boot, breaks = 50)

Diff_boot_latency_high_old <- Old_latency_high_Male_boot - Old_latency_high_Female_boot
hist(Diff_boot_latency_high_old, breaks = 50)

q16 <- quantile(Diff_boot_latency_high_old, c(0.025, 0.975)) # difference ditribuiton 95% CI
q16
m16 <- mean(Diff_boot_latency_high_old)
m16

#Contrast analysis tall tank

Tall_latency_high_Female_boot<-unlist(Tall_latency_high_Female$R_boot)
hist(Tall_latency_high_Female_boot, breaks = 50)
Tall_latency_high_Male_boot<-unlist(Tall_latency_high_Male$R_boot)
hist(Tall_latency_high_Male_boot, breaks = 50)

Diff_boot_latency_high_tall <- Tall_latency_high_Male_boot - Tall_latency_high_Female_boot
hist(Diff_boot_latency_high_tall, breaks = 50)

q17 <- quantile(Diff_boot_latency_high_tall, c(0.025, 0.975)) # difference ditribuiton 95% CI
q17
m17<- mean(Diff_boot_latency_high_tall)
m17
```

#Entries into high zone

```{r}
Model_freq_high_male <- lmer(freq_high ~ Tank + (1 | Fish_ID), data = Both_Tanks_Male)
summary(Model_freq_high_male)
hist(residuals(Model_freq_high_male))

Model_freq_high_male2 <- lmer(sqrt(freq_high) ~ Tank + (1 | Fish_ID), data = Both_Tanks_Male)
summary(Model_freq_high_male2)
hist(residuals(Model_freq_high_male2))

Model_freq_high_female <- lmer(freq_high ~ Tank + (1 | Fish_ID), data = Both_Tanks_Female)
summary(Model_freq_high_female)
hist(residuals(Model_freq_high_female))

Model_freq_high_female2 <- lmer(sqrt(freq_high) ~ Tank + (1 | Fish_ID), data = Both_Tanks_Female)
summary(Model_freq_high_female2)
hist(residuals(Model_freq_high_female2))

#Will use square root transformations as distributions look normal here

#Male analysis

Old_freq_high_Male <- rpt(sqrt(freq_high) ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_freq_high_Male

Tall_freq_high_Male <- rpt(sqrt(freq_high) ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_freq_high_Male

Joined_freq_high_Male <- rpt(sqrt(freq_high) ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Male, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Joined_freq_high_Male

#Female analysis

Old_freq_high_Female <- rpt(sqrt(freq_high) ~ (1 | Fish_ID), grname = "Fish_ID", data = Old_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Old_freq_high_Female

Tall_freq_high_Female <- rpt(sqrt(freq_high) ~ (1 | Fish_ID), grname = "Fish_ID", data = Tall_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Tall_freq_high_Female

Joined_freq_high_Female <- rpt(sqrt(freq_high) ~ Tank + (1 | Fish_ID), grname = "Fish_ID", data = Both_Tanks_Female, datatype = "Gaussian", 
    nboot = 10000, npermut = 10000)
Joined_freq_high_Female

#Contrast analysis old tank

Old_freq_high_Female_boot<-unlist(Old_freq_high_Female$R_boot)
hist(Old_freq_high_Female_boot, breaks = 50)
Old_freq_high_Male_boot<-unlist(Old_freq_high_Male$R_boot)
hist(Old_freq_high_Male_boot, breaks = 50)

Diff_boot_freq_high_old <- Old_freq_high_Female_boot - Old_freq_high_Male_boot
hist(Diff_boot_freq_high_old, breaks = 50)

q18 <- quantile(Diff_boot_freq_high_old, c(0.025, 0.975)) # difference ditribuiton 95% CI
q18
m18 <- mean(Diff_boot_freq_high_old)
m18

#Contrast analysis tall tank

Tall_freq_high_Female_boot<-unlist(Tall_freq_high_Female$R_boot)
hist(Tall_freq_high_Female_boot, breaks = 50)
Tall_freq_high_Male_boot<-unlist(Tall_freq_high_Male$R_boot)
hist(Tall_freq_high_Male_boot, breaks = 50)

Diff_boot_freq_high_tall <- Tall_freq_high_Male_boot - Tall_freq_high_Female_boot
hist(Diff_boot_freq_high_tall, breaks = 50)

q19 <- quantile(Diff_boot_freq_high_tall, c(0.025, 0.975)) # difference ditribuiton 95% CI
q19
m19 <- mean(Diff_boot_freq_high_tall)
m19

```



### Plotting repeatabilities

#Total distance sex
```{r}
Tot_Dist_rptr_sex <- tibble(
  Tank = c("Short","Short", "Tall", "Tall", "Short", "Tall"),
  Condition = c("Male","Female","Male", "Female", "Contrast", "Contrast"),
  r = c(Old_Tot_Dist_Male$R$Fish_ID,Old_Tot_Dist_Female$R$Fish_ID,Tall_Tot_Dist_Male$R$Fish_ID,Tall_Tot_Dist_Female$R$Fish_ID,mean_tot_old, mean_tot_tall ),
  ci.lb = c(Old_Tot_Dist_Male$CI_emp$`2.5%`,Old_Tot_Dist_Female$CI_emp$`2.5%`,Tall_Tot_Dist_Male$CI_emp$`2.5%`,Tall_Tot_Dist_Female$CI_emp$`2.5%`, 0.35, -0.08),
  ci.ub = c(Old_Tot_Dist_Male$CI_emp$`97.5%`,Old_Tot_Dist_Female$CI_emp$`97.5%`,Tall_Tot_Dist_Male$CI_emp$`97.5%`,Tall_Tot_Dist_Female$CI_emp$`97.5%`, 0.68, 0.45),
Endpoint = c("Total distance","Total distance","Total distance","Total distance","Total distance","Total distance"))
  
Tot_Dist_rptr_sex

plot_Tot_Dist_rptr_sex <- ggplot(Tot_Dist_rptr_sex, aes(x=Condition, y=r, colour=Sex)) +
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3), size=1.1) +
  geom_point(aes(x = Condition, y = r), position = position_dodge(0.3), size=3)+
    scale_color_manual(values=c("#FF3300","#0000FF", "#000000", "#000000"))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Tank Type", y = "r") +
  labs(title = "Repeatability estimates by sex", subtitle = "A. Total distance")+
  coord_flip()+
  ylim(-0.5, 0.9)
  #  theme(axis.title.y=element_blank(),
  #       axis.text.y=element_blank(),
  #       axis.ticks.y=element_blank())
plot_Tot_Dist_rptr_sex
```

#Low duration sex
```{r}
low_dur_rptr_sex <- tibble(
  Tank = c("Short","Short", "Tall", "Tall", "Short", "Tall"),
  Condition = c("Male","Female","Male", "Female", "Contrast", "Contrast"),
  r = c(Old_low_dur_Male$R$Fish_ID,Old_low_dur_Female$R$Fish_ID,Tall_low_dur_Male$R$Fish_ID,Tall_low_dur_Female$R$Fish_ID,m8,m9),
  ci.lb = c(Old_low_dur_Male$CI_emp$`2.5%`,Old_low_dur_Female$CI_emp$`2.5%`,Tall_low_dur_Male$CI_emp$`2.5%`,Tall_low_dur_Female$CI_emp$`2.5%`,-0.28,0.10),
  ci.ub = c(Old_low_dur_Male$CI_emp$`97.5%`,Old_low_dur_Female$CI_emp$`97.5%`,Tall_low_dur_Male$CI_emp$`97.5%`,Tall_low_dur_Female$CI_emp$`97.5%`,0.27,0.55),
Endpoint = c("Time spent in low zone","Time spent in low zone","Time spent in low zone","Time spent in low zone","Time spent in low zone","Time spent in low zone"))

low_dur_rptr_sex

plot_low_dur_rptr_sex <- ggplot(low_dur_rptr_sex, aes(x=Condition, y=r, colour=Sex)) +
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3), size=1.1) +
  geom_point(aes(x = Condition, y = r), position = position_dodge(0.3), size=3)+
    scale_color_manual(values=c("#FF3300","#0000FF", "#000000", "#000000"))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Tank Type", y = "r") +
  labs(subtitle = "E. Time spent in low zone")+
  coord_flip()+
  ylim(-0.5, 0.9)
  #  theme(axis.title.y=element_blank(),
  #       axis.text.y=element_blank(),
  #       axis.ticks.y=element_blank())
plot_low_dur_rptr_sex
```
#Mid duration
```{r}
mid_dur_rptr_sex <- tibble(
  Tank = c("Short","Short", "Tall", "Tall", "Short", "Tall"),
  Condition = c("Male","Female","Male", "Female", "Contrast", "Contrast"),
  r = c(Old_mid_dur_Male$R$Fish_ID,Old_mid_dur_Female$R$Fish_ID,Tall_mid_dur_Male$R$Fish_ID,Tall_mid_dur_Female$R$Fish_ID,m10,m11 ),
  ci.lb = c(Old_mid_dur_Male$CI_emp$`2.5%`,Old_mid_dur_Female$CI_emp$`2.5%`,Tall_mid_dur_Male$CI_emp$`2.5%`,Tall_mid_dur_Female$CI_emp$`2.5%`,-0.22,0.07),
  ci.ub = c(Old_mid_dur_Male$CI_emp$`97.5%`,Old_mid_dur_Female$CI_emp$`97.5%`,Tall_mid_dur_Male$CI_emp$`97.5%`,Tall_mid_dur_Female$CI_emp$`97.5%`,0.27,0.56),
Endpoint = c("Time spent in mid zone","Time spent in mid zone","Time spent in mid zone","Time spent in mid zone","Time spent in mid zone","Time spent in mid zone"))

mid_dur_rptr_sex

plot_mid_dur_rptr_sex <- ggplot(mid_dur_rptr_sex, aes(x=Condition, y=r, colour=Sex)) +
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3), size=1.1) +
  geom_point(aes(x = Condition, y = r), position = position_dodge(0.3), size=3)+
    scale_color_manual(values=c("#FF3300","#0000FF", "#000000", "#000000"))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Tank type", y = "r") +
  labs(subtitle = "D. Time spent in mid zone")+
  coord_flip()+
  ylim(-0.5, 0.9)
  #  theme(axis.title.y=element_blank(),
  #       axis.text.y=element_blank(),
  #       axis.ticks.y=element_blank())
plot_mid_dur_rptr_sex
```
#High duration
```{r}
high_dur_rptr_sex <- tibble(
  Tank = c("Short","Short", "Tall", "Tall", "Short", "Tall"),
  Condition = c("Male","Female","Male", "Female", "Contrast", "Contrast"),
  r = c(Old_high_dur_Male2$R$Fish_ID,Old_high_dur_Female2$R$Fish_ID,Tall_high_dur_Male2$R$Fish_ID,Tall_high_dur_Female2$R$Fish_ID,m12,m13 ),
  ci.lb = c(Old_high_dur_Male2$CI_emp$`2.5%`,Old_high_dur_Female2$CI_emp$`2.5%`,Tall_high_dur_Male2$CI_emp$`2.5%`,Tall_high_dur_Female2$CI_emp$`2.5%`,-0.13,0.07),
  ci.ub = c(Old_high_dur_Male2$CI_emp$`97.5%`,Old_high_dur_Female2$CI_emp$`97.5%`,Tall_high_dur_Male2$CI_emp$`97.5%`,Tall_high_dur_Female2$CI_emp$`97.5%`,0.36,0.51),
Endpoint = c("Time spent in high zone","Time spent in high zone","Time spent in high zone","Time spent in high zone","Time spent in high zone","Time spent in high zone"))

high_dur_rptr_sex

plot_high_dur_rptr_sex <- ggplot(high_dur_rptr_sex, aes(x=Condition, y=r, colour=Sex)) +
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3), size=1.1) +
  geom_point(aes(x = Condition, y = r), position = position_dodge(0.3), size=3)+
    scale_color_manual(values=c("#FF3300","#0000FF", "#000000", "#000000"))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Tank Type", y = "r") +
  labs(subtitle = "C. Time spent in high zone")+
  coord_flip()+
  ylim(-0.5, 0.9)
  #  theme(axis.title.y=element_blank(),
  #       axis.text.y=element_blank(),
  #       axis.ticks.y=element_blank())
plot_high_dur_rptr_sex
```

#Freezing duration
```{r}
freezing_dur_rptr_sex <- tibble(
  Tank = c("Short","Short", "Tall", "Tall", "Short", "Tall"),
  Condition = c("Male","Female","Male", "Female", "Contrast", "Contrast"),
  r = c(Old_freezing_dur_Male3$R$Fish_ID,Old_freezing_dur_Female3$R$Fish_ID,Tall_freezing_dur_Male3$R$Fish_ID,Tall_freezing_dur_Female3$R$Fish_ID,m14,m15),
  ci.lb = c(Old_freezing_dur_Male3$CI_emp$`2.5%`,Old_freezing_dur_Female3$CI_emp$`2.5%`,Tall_freezing_dur_Male3$CI_emp$`2.5%`,Tall_freezing_dur_Female3$CI_emp$`2.5%`,0.03,-0.25),
  ci.ub = c(Old_freezing_dur_Male3$CI_emp$`97.5%`,Old_freezing_dur_Female3$CI_emp$`97.5%`,Tall_freezing_dur_Male3$CI_emp$`97.5%`,Tall_freezing_dur_Female3$CI_emp$`97.5%`,0.56,0.32),
Endpoint = c("Time spent freezing","Time spent freezing","Time spent freezing","Time spent freezing","Time spent freezing","Time spent freezing"))

freezing_dur_rptr_sex

plot_freezing_dur_rptr_sex <- ggplot(freezing_dur_rptr_sex, aes(x=Condition, y=r, colour=Sex)) +
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3), size=1.1) +
  geom_point(aes(x = Condition, y = r), position = position_dodge(0.3), size=3)+
    scale_color_manual(values=c("#FF3300","#0000FF", "#000000", "#000000"))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Tank Type", y = "r") +
  labs(subtitle = "B. Time spent freezing")+
  coord_flip()+
  ylim(-0.5, 0.9)
  #  theme(axis.title.y=element_blank(),
  #       axis.text.y=element_blank(),
  #       axis.ticks.y=element_blank())
plot_freezing_dur_rptr_sex
```
#Latency high
```{r}
latency_high_rptr_sex <- tibble(
  Tank = c("Short","Short", "Tall", "Tall", "Short", "Tall"),
  Condition = c("Male","Female","Male", "Female", "Contrast", "Contrast"),
  r = c(Old_latency_high_Male$R$Fish_ID,Old_latency_high_Female$R$Fish_ID,Tall_latency_high_Male$R$Fish_ID,Tall_latency_high_Female$R$Fish_ID,m16,m17),
  ci.lb = c(Old_latency_high_Male$CI_emp$`2.5%`,Old_latency_high_Female$CI_emp$`2.5%`,Tall_latency_high_Male$CI_emp$`2.5%`,Tall_latency_high_Female$CI_emp$`2.5%`,-0.31,0.16),
  ci.ub = c(Old_latency_high_Male$CI_emp$`97.5%`,Old_latency_high_Female$CI_emp$`97.5%`,Tall_latency_high_Male$CI_emp$`97.5%`,Tall_latency_high_Female$CI_emp$`97.5%`,0.34,0.68),
Endpoint = c("Latency to high zone","Latency to high zone","Latency to high zone","Latency to high zone","Latency to high zone","Latency to high zone"))

latency_high_rptr_sex

plot_latency_high_rptr_sex <- ggplot(latency_high_rptr_sex, aes(x=Condition, y=r, color=Sex)) +
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3), size=1.1) +
  geom_point(aes(x = Condition, y = r), position = position_dodge(0.3), size=3)+
    scale_color_manual(values=c("#FF3300","#0000FF", "#000000", "#000000"))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Tank Type", y = "r") +
  labs(subtitle = "Latency to high zone")+
  coord_flip()+
  ylim(-0.5, 0.9)
  #  theme(axis.title.y=element_blank(),
  #       axis.text.y=element_blank(),
  #       axis.ticks.y=element_blank())
plot_latency_high_rptr_sex
```

#Entries to high
```{r}
freq_high_rptr_sex <- tibble(
  Tank = c("Short","Short", "Tall", "Tall", "Short", "Tall"),
  Condition = c("Male","Female","Male", "Female", "Contrast", "Contrast"),
  r = c(Old_freq_high_Male$R$Fish_ID,Old_freq_high_Female$R$Fish_ID,Tall_freq_high_Male$R$Fish_ID,Tall_freq_high_Female$R$Fish_ID,m18,m19 ),
  ci.lb = c(Old_freq_high_Male$CI_emp$`2.5%`,Old_freq_high_Female$CI_emp$`2.5%`,Tall_freq_high_Male$CI_emp$`2.5%`,Tall_freq_high_Female$CI_emp$`2.5%`,-0.07,0.12),
  ci.ub = c(Old_freq_high_Male$CI_emp$`97.5%`,Old_freq_high_Female$CI_emp$`97.5%`,Tall_freq_high_Male$CI_emp$`97.5%`,Tall_freq_high_Female$CI_emp$`97.5%`,0.43,0.62),
Endpoint = c("Entries into high zone","Entries into high zone","Entries into high zone","Entries into high zone","Entries into high zone","Entries into high zone"))

freq_high_rptr_sex

plot_freq_high_rptr_sex <- ggplot(freq_high_rptr_sex, aes(x=Tank_Type, y=r, colour=Sex)) +
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3), size=1.1) +
  geom_point(aes(x = Tank_Type, y = r), position = position_dodge(0.3), size=3)+
    scale_color_manual(values=c("#FF3300","#0000FF", "#000000", "#000000"))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Tank Type", y = "r") +
  labs(subtitle = "Entries to high")+
  coord_flip()+
  ylim(-0.5, 0.9)
  #  theme(axis.title.y=element_blank(),
  #       axis.text.y=element_blank(),
  #       axis.ticks.y=element_blank())
plot_freq_high_rptr_sex
```









