---
title: "Additional Analyses"
author: "Hamza"
date: "8/10/2020"
output: html_document
---

### Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


#install.packages("pacman")
#install.packages("ggThemeAssist")
#install.packages("ggbeeswarm")
#install.packages("rptR")
#install.packages("lme4")
#install.packages("lmerTest")
#install.packages("wesanderson")
library(lmerTest)
library(ggThemeAssist)
library(rptR)
library(lme4)
library(readxl)
library(dplyr)
pacman::p_load(readxl, tidyr, dplyr, magrittr, lubridate, stringr, purrr)
library(sjPlot)
library(ggplot2)
library(lubridate)
library(wesanderson)
library(ggbeeswarm)
library(emmeans)
library(patchwork)
library(viridis)
library(nlme)
library(Rmisc)
#sessionInfo()
```

#Tables
```{r}
mixed_model_tables <- tab_model(mixed_model_total_distance, mixed_model_low_dur, mixed_model_mid_dur, mixed_model_high_dur, mixed_model_freezing_dur, mixed_model_latency_high, mixed_model_freq_high,collapse.ci = TRUE,  file = "tables.docx")

mixed_model_tables
```










